version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - currency-network
      
  currency-exchange:
    depends_on:
      - mysqldb
    image: bojan92/ce-currency-exchange-service:0.0.1
    restart: on-failure
    env_file: ./.env
    ports:
      - "8000:8000"
    networks:
      - currency-network
    environment:
      SPRING_APPLICATION_JSON: '{
        "eureka.client.serviceUrl.defaultZone" : "http://naming-server:8761/eureka",
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  naming-server:
    image: bojan92/ce-naming-server:0.0.1
    ports:
      - "8761:8761"
    networks:
      - currency-network
      
networks:
  currency-network:

volumes:
  db: